apiVersion: v1
kind: Namespace
metadata:
  name: devops-app
  labels:
    app.kubernetes.io/name: devops-portfolio-app
    app.kubernetes.io/part-of: devops-platform
    environment: production
  annotations:
    description: "Namespace for the DevOps Portfolio Platform application"
